

--GRANT USAGE ON DATABASE SNOWPARK_STREAMLIT TO ROLE <your_role>;
--GRANT USAGE ON SCHEMA SNOWPARK_STREAMLIT.STAGING TO ROLE <your_role>;
--GRANT CREATE STAGE ON SCHEMA  SNOWPARK_STREAMLIT.STAGING  TO ROLE <your_role>;
GRANT CREATE STREAMLIT ON SCHEMA  SNOWPARK_STREAMLIT.STAGING  TO ROLE ACCOUNTADMIN;
